name: arm-none-eabi-gcc CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: boot
        run: ./build.sh boot

      - name: hello1
        run: ./build.sh hello1

      - name: hello2
        run: ./build.sh hello2
